# Generated by Django 4.1.1 on 2022-10-01 13:21

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('UserFirstName', models.CharField(max_length=255)),
                ('UserLastName', models.CharField(max_length=255)),
                ('UserCPF', models.CharField(max_length=12)),
                ('UserEmail', models.CharField(max_length=255)),
                ('UserStats', models.BooleanField(choices=[(True, 'Ativo'), (False, 'Inativo')])),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('GpId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('GpName', models.CharField(max_length=255)),
                ('GpStats', models.BooleanField(choices=[(True, 'Ativo'), (False, 'Inativo')])),
                ('GpUse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='GrupoUsers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Financas',
            fields=[
                ('FinancaID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('FinancaType', models.BooleanField(choices=[(True, 'Entrada'), (False, 'Saida')])),
                ('FinancaValue', models.FloatField()),
                ('FinancaDateCreate', models.DateTimeField(auto_now_add=True, null=True)),
                ('FinancaDateUpdate', models.DateTimeField(auto_now=True, null=True)),
                ('FinancaStats', models.BooleanField(choices=[(True, 'Ativo'), (False, 'Inativo')])),
                ('FinancaGroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Data.groups')),
            ],
        ),
        migrations.CreateModel(
            name='Caixas',
            fields=[
                ('CaixaID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('CaixaTotal', models.FloatField()),
                ('CaixaStats', models.BooleanField(choices=[(True, 'Ativo'), (False, 'Inativo')])),
                ('CaixaFinanca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Data.financas')),
            ],
        ),
    ]
