# Generated by Django 4.1.1 on 2022-11-21 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='CmMessageEnglish',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
