# Generated by Django 4.1.1 on 2022-11-21 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data', '0002_comentario_cmmessageenglish'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='CmScoreIA',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
