# Generated by Django 4.1.1 on 2022-11-21 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data', '0003_comentario_cmscoreia'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentario',
            old_name='CmScoreIA',
            new_name='CmScoreIA_logistica',
        ),
        migrations.AddField(
            model_name='comentario',
            name='CmScoreIA_neural',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
